title: Fire Learn
description: Learning site for FIRE!
exclude: [README.md]
include: [".well-known"]

# applies pretty for all
permalink: pretty
plugins:
  - jekyll-relative-links

repository: firelearn/learn-theme@v0.1.2
remote_theme: firelearn/learn-theme@v0.1.2